pipeline:
  name: iac-teju2
  identifier: iacteju2
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: provision
        identifier: provision
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: tejuworkspace
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - parallel:
                  - step:
                      type: IACMTerraformPlugin
                      name: apply
                      identifier: apply
                      timeout: 10m
                      spec:
                        command: apply
                      when:
                        stageStatus: Success
                        condition: <+pipeline.variables.inputchoice>=="apply"
                  - step:
                      type: IACMTerraformPlugin
                      name: IACMTerraformPlugin_4
                      identifier: IACMTerraformPlugin_4
                      spec:
                        command: destroy
                      timeout: 1h
                      when:
                        stageStatus: Success
                        condition: <+pipeline.variables.inputchoice>=="destroy"
        tags: {}
  variables:
    - name: inputchoice
      type: String
      description: ""
      required: false
      value: <+input>.allowedValues(apply,destroy)
